services:
  surrealdb:
    image: surrealdb/surrealdb:v2
    command: start --user root --pass password --bind 0.0.0.0:8000 rocksdb:/mydata/mydatabase.db
    ports:
      - "8000:8000"
    volumes:
      - ./surreal_data:/mydata

  backpack:
    image: lfnovo/backpack:local
    pull_policy: never
    ports:
      - "8502:8502"  # Web UI
      - "5055:5055"  # API
      - "5678:5678"  # debugpy
    environment:
      # Your OpenAI key
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LOG_LEVEL=DEBUG
      # Database (required)
      - SURREAL_URL=ws://surrealdb:8000/rpc
      - SURREAL_USER=root
      - SURREAL_PASSWORD=${SURREAL_PASSWORD}
      - SURREAL_NAMESPACE=backpack
      - SURREAL_DATABASE=backpack
    volumes:
      - ./module_data:/app/data
      - ./api:/app/api
      - ./backpack:/app/backpack
      - ./commands:/app/commands
    depends_on:
      - surrealdb
    restart: always